### PR TITLE
Fix link memory catz

### PR DESCRIPTION
**Pull request by jkarnowski**
:smile_cat:

### CODE REVIEW

**Comment by jkarnowski** [comment]
Hey Gaby,

Happy Friday!
I just went to the PairUp Memory Game page and noticed that the page
http://www.pairuptocode.com/exercises/memorygame.html is not the updated
version that you had merged. It still has the broken LOLCat on it. Call me
crazy but if you merged the PR, shouldn't the page show those changes?

Cheers,

Jaclyn

On Mon, Jan 18, 2016 at 11:17 AM Eva Gabriela notifications@github.com
wrote:

> Merged #12 https://github.com/evagabriela/pairup/pull/12.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/evagabriela/pairup/pull/12#event-518281765.
> 
> ## 
> 
> Jaclyn Karnowski

freelance web developer
co-founder, EdTalks

**Comment by evagabriela** [comment]
Hi Jaclyn,
I found the issue.  the changes appear to be in master but not in gh-pages
and because the site is live through gh-pages, we cant see the updtes on
that page.  I will fix it when I get home or tomorrow morning :)

Thanks for brining it to my attention
Gaby

**Comment by evagabriela** [comment]
Hi Jaclyn,

I just pushed the changes.  Please let me know if you dont see the updates
within couple hours.

Best,

gaby

**Comment by pamelafox** [comment]
Check out this blog post for a way to set up your repo locally so it always pushes to both master and gh-pages:
http://brettterpstra.com/2012/09/26/github-tip-easily-sync-your-master-to-github-pages/

**Comment by evagabriela** [comment]
Cool! Thank you. I needed to do that :)

**Pull request merged**
